- agrochain/src/App.js
- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added register component

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Fixed chart.js

- agrochain/src/Components/Navigation.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: imporved Navigation bar

- agrochain/src/App.js
- agrochain/src/Components/Front.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added Front Page

- agrochain/src/Components/Front.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: UI fixes

- agrochain/src/App.js
- agrochain/src/Components/NFT.js
* Hardware:
* Toolchain:
* SDK:
> search & sort filter changes

- agrochain/package-lock.json
- agrochain/package.json
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added axios package

- agrochain/src/Components/NFT.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: temporary fix of the search bar UI

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added Axios

- agrochain/package.json
- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: updated fetching data from API and CQRS

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: added settimer function to update graph with latest values

- agrochain/src/App.js
- agrochain/src/Components/NFT.js
- agrochain/src/Components/NFTDetails.js
- agrochain/src/Components/Navigation.js
- agrochain/src/Components/Profile.js
- agrochain/src/Components/Register.js
- agrochain/src/frontend/NftContext/NftProvider.js
- agrochain/src/index.js
* Hardware:
* Toolchain:
* SDK:
> page refresh error fix

- agrochain/src/Components/NFTDetails.js
- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Register page UI fixes

- OCR/app.py
- OCR/requirements.txt
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added OCR functionality

- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> :earth_asia: Fixed Latitude, Longitude issue in the Registration Page

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :world_map: NFT Details Page and Load Pollution Data API

- agrochain/src/Components/Profile.js
- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> profile fix changes

- agrochain/src/App.js
- agrochain/src/Components/Navigation.js
- agrochain/src/Components/Register.js
- agrochain/src/frontend/NftContext/NftProvider.js
- agrochain/src/frontend/NftContext/nftActions.js
- agrochain/src/frontend/NftContext/nftReducer.js
* Hardware:
* Toolchain:
* SDK:
> profile fix

- agrochain/src/Components/Navigation.js
- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> Profile UI Fix

- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: updated the Register UI

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Graphs

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Updated the NFT Details Page

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> loadPollutionData API call fix

- .gitignore
- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Imporved NFT Details UI and Added Carbon Credit Certificate

- OCR/app.py
* Hardware:
* Toolchain:
* SDK:
> :wrench: OCR Fix

- agrochain/src/Components/NFT.js
- agrochain/src/Components/NFTDetails.js
- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Updated the UI

- agrochain/src/Components/Front.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Deleted Video

- agrochain/src/Components/Front.js
Reverts IntelegixLabs/AgroChain#60
> Revert ":wrench: Deleted Video"

- agrochain/src/Components/NFTDetails.js
* Hardware:
* Toolchain:
* SDK:
> :world_map: Added Maps in Certificate

- amplify.yml
* Hardware:
* Toolchain:
* SDK:
> deploying with AWS Amplify changes

- agrochain/src/Components/NFT.js
- agrochain/src/Components/NFTDetails.js
- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Updated Ethereum Icons (Don't Merge)

- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> updated maps to current location

- agrochain/src/App.css
- agrochain/src/Components/Certificate/certificate.css
- agrochain/src/Components/Certificate/certificate.js
* Hardware:
* Toolchain:
* SDK:
> Added new component for certificate and downloaded pdf

- agrochain/src/Components/NFT.js
- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Caron Emission Tab

- agrochain/src/Components/Front.js
- agrochain/src/Components/Navigation.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: UI Changes

- agrochain/package-lock.json
- agrochain/package.json
- agrochain/src/App.js
- agrochain/src/Components/Certificate/certificate.css
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added Certificate

- agrochain/.dockerignore
- agrochain/Dockerfile
- agrochain/src/App.js
- agrochain/src/Components/Certificate/certificate.js
* Hardware:
* Toolchain:
* SDK:
> certificate issue fix & added dockerfile

- agrochain/src/App.js
- agrochain/src/Components/Certificate/certificate.js
- agrochain/src/Components/NFTDetails.js
- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Integrated certificate

- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: UI Fix

- agrochain/src/Components/NFTDetails.js
- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Cleanup the Code

- agrochain/src/Components/NFTDetails.js
- agrochain/src/Components/Profile.js
- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: removing console logs

- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> marker postion fix

- agrochain/src/Components/form/index.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Adding Payment Accept button

- agrochain/src/Components/card/index.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Updated the image url

- agrochain/src/Components/Profile.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Updated the ipfs end point

- agrochain/package-lock.json
- agrochain/package.json
- agrochain/src/Components/card/index.js
- agrochain/src/Components/index.js
- agrochain/src/setupProxy.js
* Hardware:
* Toolchain:
* SDK:
> Rapyd pai integration

- agrochain/src/Components/index.js
* Hardware:
* Toolchain:
* SDK:
> Rapyd API integration

- agrochain/src/Components/form/index.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added space

- agrochain/src/Components/form/index.js
- agrochain/src/Components/index.js
* Hardware:
* Toolchain:
* SDK:
> payment button changes

- Rapyd.All/Rapyd.API/Program.cs
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added cqrs policy

- agrochain/src/Components/Register.js
* Hardware:
* Toolchain:
* SDK:
> :wrench: Added RapydId Key Generation in the Register Id

- agrochain/src/Components/Profile.js
- agrochain/src/Components/Register.js
- agrochain/src/backend/contracts/Marketplace.sol
* Hardware:
* Toolchain:
* SDK:
> :wrench: Rapyd API Integration for customer creation
